[package]
name = "pain-ts-"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.5"
pixels = "0.13.0"
wgpu = "0.17.0"
wgpu_glyph = "0.21.0"
winit = "0.28.0"
